

public class PrincipalUI extends javax.swing.JFrame {

	    /**
	     * Creates new form PrincipalUI
	     */
	    private MainConnection connection;
	    public PrincipalUI(MainConnection connection) {
	    	this.connection = connection;
	        initComponents();
	        this.setResizable(false);
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jPanel1 = new javax.swing.JPanel();
	        jButton1 = new javax.swing.JButton();
	        jButton3 = new javax.swing.JButton();
	        jButton2 = new javax.swing.JButton();
	        jSeparator1 = new javax.swing.JSeparator();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	        setPreferredSize(new java.awt.Dimension(655, 400));

	        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
	        jPanel1.setPreferredSize(new java.awt.Dimension(653, 334));
	        jPanel1.setLayout(null);

	        jButton1.setBackground(new java.awt.Color(0, 204, 51));
	        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
	        jButton1.setForeground(new java.awt.Color(0, 0, 0));
	        jButton1.setText("Gestionar Libros");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jButton1);
	        jButton1.setBounds(220, 80, 220, 29);

	        jButton3.setText("Cerrar sesión");
	        jButton3.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton3ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jButton3);
	        jButton3.setBounds(260, 250, 140, 30);

	        jButton2.setBackground(new java.awt.Color(0, 204, 51));
	        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
	        jButton2.setForeground(new java.awt.Color(0, 0, 0));
	        jButton2.setText("Gestionar Administradores");
	        jButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton2ActionPerformed(evt);
	            }
	        });
	        jPanel1.add(jButton2);
	        jButton2.setBounds(220, 140, 222, 29);

	        jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
	        jPanel1.add(jSeparator1);
	        jSeparator1.setBounds(100, 200, 450, 1);

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	        );

	        pack();
	        this.setLocationRelativeTo(null);
	    }// </editor-fold>                        

	    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        System.out.println("Boton gestionar libros");
	    }                                        

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) { 
	    	this.dispose();
	    	ManageBookUI mui = new ManageBookUI(this.connection);
	    	mui.setVisible(true);
	    
	    }                                        

	    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	       System.out.println("Boton cerrar sesion");
	    }                                        

	  

	    // Variables declaration - do not modify                     
	    private javax.swing.JButton jButton1;
	    private javax.swing.JButton jButton2;
	    private javax.swing.JButton jButton3;
	    private javax.swing.JPanel jPanel1;
	    private javax.swing.JSeparator jSeparator1;
}
